function [pos_Xray_D, pos_Yray_D, pos_Zray_D, collect_circles] = field_funY(z_rotation, surf_z_coord, ...
    ang_Xray_axis10, ang_Yray_axis10, detector_ang, surf_half_length, ...
    pos_Xray10, pos_Yray10, pos_Zray10, prism_thickness, loop_ind, prism_no, ...
    rotate_about_z1, rotate_about_z2, rotate_about_z3, rotate_about_z30, rotate_about_z4)

[norm_x, norm_y] = surface_norms(detector_ang, z_rotation);
[X_grid, Y_grid, Z_grid] = prism_surf(norm_x, norm_y, surf_half_length);
[pos_Xray_D, pos_Yray_D, pos_Zray_D] = ray_coord(pos_Xray10, pos_Yray10, ...
    pos_Zray10, ang_Xray_axis10, ang_Yray_axis10, surf_z_coord, ...
    X_grid, Y_grid, Z_grid, norm_x, norm_y);
ray_x = [pos_Xray10, pos_Xray_D];
ray_y = [pos_Yray10, pos_Yray_D];
ray_z = [pos_Zray10, pos_Zray_D];

[~, ~] = plt_layout(ray_x, ray_y, ray_z, ray_x, ray_y, ray_z, ...
    X_grid, Y_grid, Z_grid, Z_grid, surf_z_coord, prism_thickness, prism_no);

[collect_circles] = plt_detector(rotate_about_z3, rotate_about_z30, loop_ind, ...
    pos_Xray_D, pos_Yray_D, surf_half_length);

[~] = plt_rotation(rotate_about_z1, rotate_about_z2, rotate_about_z3, ...
    rotate_about_z4);