function [ang_Xray_axis21, ang_Yray_axis21, pos_Xray21, pos_Yray21, pos_Zray21] = ...
    prism_funY(z_rotation, surf_z_coord1, ang_Xray_axis10, ang_Yray_axis10, ...
    prism_ang1, prism_ang2, surf_half_length, n_air, n_glass, pos_Xray10, ...
    pos_Yray10, pos_Zray10, prism_thickness, prism_no)

[norm_x1, norm_y1] = surface_norms(prism_ang1, z_rotation);                  % surface normal angles (tilt about x and y axis)
[X_grid, Y_grid, Z_grid1] = prism_surf(norm_x1, norm_y1, surf_half_length);   % prism surface coordinates  
[ang_Xray_norm10, ang_Yray_norm10] = incident_angs ...
    (ang_Xray_axis10, ang_Yray_axis10, norm_x1, norm_y1);                    % incident ray angles wrt 1st surface normal
[ang_Xray_axis11, ang_Yray_axis11] = snellsLaw ...
    (norm_x1, norm_y1, ang_Xray_norm10, ang_Yray_norm10, n_air, n_glass);    % ray angles after refraction from 1 surface
[pos_Xray11, pos_Yray11, pos_Zray11] = ray_coord(pos_Xray10, pos_Yray10, ...
    pos_Zray10, ang_Xray_axis10, ang_Yray_axis10, surf_z_coord1, X_grid, ...
    Y_grid, Z_grid1, norm_x1, norm_y1);
ray_x01 = [pos_Xray10, pos_Xray11];
ray_y01 = [pos_Yray10, pos_Yray11];
ray_z01 = [pos_Zray10, pos_Zray11];

surf_z_coord2 = surf_z_coord1 + prism_thickness;
[norm_x2, norm_y2] = surface_norms(prism_ang2, z_rotation);                  % surface normal angles (tilt about x and y axis)
[X_grid, Y_grid, Z_grid2] = prism_surf(norm_x2, norm_y2, surf_half_length);  % prism surface coordinates
[ang_Xray_norm20, ang_Yray_norm20] = incident_angs( ...
    ang_Xray_axis11, ang_Yray_axis11, norm_x2, norm_y2);                     % incident ray angles wrt 1st surface normal
[ang_Xray_axis21, ang_Yray_axis21] = snellsLaw ...
    (norm_x2, norm_y2, ang_Xray_norm20, ang_Yray_norm20, n_glass, n_air);    % ray angles after refraction from 1st surface
[pos_Xray21, pos_Yray21, pos_Zray21] = ray_coord(pos_Xray11, pos_Yray11, ...
    pos_Zray11, ang_Xray_axis11, ang_Yray_axis11, surf_z_coord2, X_grid, ...
    Y_grid, Z_grid2, norm_x1, norm_y1);                                      % ray position on the current surface      

ray_x12 = [pos_Xray11, pos_Xray21];                                          % ray segment coordinates 
ray_y12 = [pos_Yray11, pos_Yray21];
ray_z12 = [pos_Zray11, pos_Zray21];

[~, ~] = plt_layout(ray_x01, ray_y01, ray_z01, ray_x12, ray_y12, ray_z12, ...
    X_grid, Y_grid, Z_grid1, Z_grid2, surf_z_coord1, prism_thickness, prism_no);